import { Request, Response } from "express";
import { z } from "zod";
import { parseFilesForShipmentData } from "../services/ai/parseFiles";
import { createShipmentAgent, getShipmentAgent } from "../agent/shipmentAgent";
import { ChecklistItem, ShipmentInput } from "../types/types";
import { generateShipmentDocuments } from "../services/documents/generator";
import { getTransitCountries } from "../services/route/geoapify";

const shipmentSchema = z.object({
  origin: z.string().optional(),
  destination: z.string().optional(),
  description: z.string().optional(),
  weight: z.coerce.number().optional(),
  value: z.coerce.number().optional(),
  shipDate: z.string().optional(),
  files: z.any().optional(),
});

const safeParse = (text: string) => {
  try {
    return JSON.parse(text);
  } catch {
    const match = text.match(/\{[\s\S]*\}/);
    if (match) return JSON.parse(match[0]);
    return null;
  }
};

export const processShipment = async (req: Request, res: Response) => {
  try {
    const files = req.files as Express.Multer.File[] | undefined;
    const hasFiles = files && files.length > 0;

    let input: z.infer<typeof shipmentSchema>;

    if (hasFiles) {
      input = await parseFilesForShipmentData(files);
    } else {
      const parsed = shipmentSchema.safeParse(req.body);
      if (!parsed.success) {
        return res.status(400).json({
          error: "Invalid input",
          details: parsed.error.format(),
        });
      }
      input = parsed.data;
    }

    // Паралельно: отримуємо агента і транзитні країни
    const [{ agent }, transitCountries] = await Promise.all([
      getShipmentAgent(),
      getTransitCountries(input.origin ?? "", input.destination ?? ""),
    ]);

    const transitCodes = transitCountries.map((c) => c.name).join(", ");

    const agentInput = `
      Process this shipment:
      - Product: ${input.description ?? "unknown"}
      - Origin: ${input.origin ?? "unknown"}
      - Destination: ${input.destination ?? "unknown"}
      - Transit countries: ${transitCodes || "unknown"}
      - Weight: ${input.weight ?? "unknown"} kg
      - Value: ${input.value ?? "unknown"}
      - Ship date: ${input.shipDate ?? "unknown"}
    `;

    const agentResult = await agent.invoke({
      messages: [{ role: "user", content: agentInput }],
    });

    // Агент повертає JSON у output
    const lastMessage = agentResult.messages[agentResult.messages.length - 1];
    const parsed = safeParse(lastMessage?.content as string);

    const AUTO_GENERATED_IDS = ["cmr", "commercial-invoice", "packing-list"];

    if (parsed?.checklist) {
      parsed.checklist = parsed.checklist.map((item: ChecklistItem) => {
        const isAutoGenerated = AUTO_GENERATED_IDS.some(
          (id) =>
            item.id?.includes(id) ||
            item.name?.toLowerCase().includes("cmr") ||
            item.name?.toLowerCase().includes("invoice") ||
            item.name?.toLowerCase().includes("packing"),
        );
        if (isAutoGenerated) {
          return { ...item, status: "generated", canAutoGenerate: true };
        }
        return item;
      });
    }

    const documents = await generateShipmentDocuments(
      input as ShipmentInput,
      parsed?.hsCode?.hsCode ?? "000000",
    );

    return res.json({
      input,
      ...parsed,
      documents,
      transitCountries,
    });
  } catch (error) {
    console.error("Process shipment error:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
};
